//! Adoption scaffolding — `synthesize --init`.
//!
//! For a fork adopting declarative synthesis: discover open PRs with heads
//! in the fork as patch proposals, create a control branch locally (from the
//! upstream tip, or a fresh root with `--fresh`), and write the managed
//! files (caller workflows, `synthesis.json`) into it for review.
//!
//! Deliberately additive-only: branch creation, file writes, and one local
//! commit. It never pushes (unless `--push`), never touches the default
//! branch, never deletes. The consequential steps — flipping the default
//! branch in settings, triggering the first synthesis — stay human, listed
//! at the end of every run.
//!
//! The generated config pins nothing yet (no lockfile is written): the first
//! synthesis bootstraps it, and reviewing those SHAs is load-bearing.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

use crate::config::{BranchRef, PatchSpec, Repo, Strategy, SynthesisConfig};
use crate::update::OpenPr;

/// A patch proposal from discovery: the head branch plus the PR that
/// justifies it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProposedPatch {
    /// Where the patch lives.
    pub branch: BranchRef,
    /// The open PR number proposing it.
    pub pr_number: u64,
}

/// Propose patches from open PRs: one per distinct head repo+branch, ordered
/// by PR number, skipping anything in `exclude` (base, output, and the
/// nascent control branch itself).
pub fn propose_patches(prs: &[OpenPr], exclude: &[BranchRef]) -> Vec<ProposedPatch> {
    let mut ordered: Vec<&OpenPr> = prs.iter().collect();
    ordered.sort_by_key(|pr| pr.number);
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for pr in ordered {
        let branch = BranchRef {
            repo: Repo {
                owner: pr.head_owner.clone(),
                name: pr.head_name.clone(),
            },
            branch: pr.head_ref.clone(),
        };
        if exclude
            .iter()
            .any(|e| e.repo.slug() == branch.repo.slug() && e.branch == branch.branch)
        {
            continue;
        }
        if !seen.insert((branch.repo.slug(), branch.branch.clone())) {
            continue;
        }
        out.push(ProposedPatch {
            branch,
            pr_number: pr.number,
        });
    }
    out
}

/// Options for [`scaffold`].
pub struct InitOptions {
    /// Upstream base (e.g. `integrations/repo@main`).
    pub base: BranchRef,
    /// The fork being adopted.
    pub fork: Repo,
    /// Output branch name (in the fork). Defaults to `main`.
    pub output_branch: String,
    /// Control branch to create (holds managed files). Defaults to
    /// `fork-owned`.
    pub control_branch: String,
    /// Fresh root commit instead of forking the upstream tip.
    pub fresh: bool,
    /// Engine ref to pin in generated caller workflows.
    pub engine_ref: String,
}

/// Paths written by [`scaffold`], for reporting.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Scaffolded {
    /// Control branch created.
    pub branch: String,
    /// Files written, relative to the workdir.
    pub files: Vec<String>,
    /// Proposed patches in the generated config.
    pub patches: Vec<ProposedPatch>,
}

/// Generate the managed file contents for a fresh adoption.
///
/// Pure string building (no I/O): the caller workflow pair plus
/// `synthesis.json` with discovered patches. The control branch itself
/// leads as an unpinned first layer so its files reach the output.
pub fn render_files(
    base: &BranchRef,
    fork: &Repo,
    output_branch: &str,
    control: &BranchRef,
    patches: &[ProposedPatch],
    engine_pin: &str,
) -> Vec<(String, String)> {
    let output = BranchRef {
        repo: fork.clone(),
        branch: output_branch.to_string(),
    };
    let synthesize_yml = format!(
        r#"# Managed synthesis: declarative base + patches -> output.
#
# Generated by `synthesize --init`; human-owned from here. Triggers: daily
# schedule for upstream drift, pushes to patch branches for immediacy,
# manual runs. The output branch is rebuilt (force-pushed) every run —
# never commit to it directly.
name: Synthesize

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [{push_branches}]
  workflow_dispatch:

jobs:
  synthesize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency:
      group: synthesize-{output_branch}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: jonathanmorley/fork-maintainer@{engine_pin}
        id: synthesize
        with:
          config: synthesis.json
          lockfile: synthesis.lock
          token: ${{ github.token }}
      - name: Report outcome
        run: echo "pushed=${{ steps.synthesize.outputs.pushed }} commit=${{ steps.synthesize.outputs.commit }}"
"#,
        push_branches = push_branches(fork, patches),
        output_branch = output_branch,
        engine_pin = engine_pin,
    );
    let update_yml = r#"# Maintenance proposals: lock refresh + merged-patch removal as PRs.
#
# Generated by `synthesize --init`; human-owned from here. Weekly schedule
# plus manual runs (with optional dry-run preview). Merge each proposal;
# the next synthesis reflects it. Never pushes output, deletes branches,
# or closes PRs.
name: Propose synthesis updates

on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Preview without opening a PR"
        type: boolean
        default: false

jobs:
  update:
    uses: UPDATE_WORKFLOW_REF
    permissions:
      contents: write
      pull-requests: write
    with:
      config: synthesis.json
      lockfile: synthesis.lock
      dry-run: ${{ inputs.dry-run }}
"#
    .replace(
        "UPDATE_WORKFLOW_REF",
        &format!("jonathanmorley/fork-maintainer/.github/workflows/update.yml@{engine_pin}"),
    );
    let config = SynthesisConfig {
        base: base.clone(),
        patches: std::iter::once(PatchSpec {
            branch: control.clone(),
            pin: false,
        })
        .chain(patches.iter().map(|p| PatchSpec {
            branch: p.branch.clone(),
            pin: true,
        }))
        .collect(),
        output,
        strategy: Strategy::Merge,
    };
    let config_json = serde_json::to_string_pretty(&config).expect("config serializes");
    vec![
        (
            ".github/workflows/synthesize.yml".to_string(),
            synthesize_yml,
        ),
        (".github/workflows/update.yml".to_string(), update_yml),
        ("synthesis.json".to_string(), format!("{config_json}\n")),
    ]
}

/// Push-trigger branches: the fork's own patch branches (cross-repo pushes
/// land elsewhere and cannot trigger these workflows).
fn push_branches(fork: &Repo, patches: &[ProposedPatch]) -> String {
    let mut branches: Vec<String> = patches
        .iter()
        .filter(|p| p.branch.repo.slug() == fork.slug())
        .map(|p| p.branch.branch.clone())
        .collect();
    branches.sort();
    branches.dedup();
    branches
        .iter()
        .map(|b| format!("\"{b}\""))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Run a git command in `dir`, returning stdout trimmed.
///
/// # Errors
///
/// Returns an error when git cannot execute or exits non-zero.
fn git(dir: &Path, args: &[&str]) -> Result<String> {
    let output = std::process::Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .output()
        .with_context(|| format!("failed to execute git {}", args.join(" ")))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("git {} failed: {stderr}", args.join(" "));
    }
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

/// Scaffold an adoption in `workdir` (a checkout of the fork).
///
/// Verifies a clean worktree, resolves the upstream tip, turns `open` PRs
/// into patch proposals, creates the control branch (from the tip, or a
/// fresh root with `opts.fresh`), writes and commits the managed files.
/// Never pushes unless `push` is set. Returns what was created plus the
/// human next steps.
///
/// # Errors
///
/// Returns an error when the worktree is dirty, the branch exists, the
/// network calls fail, or any git operation fails.
pub fn scaffold(
    workdir: &Path,
    opts: &InitOptions,
    open: &[OpenPr],
    url_for: &dyn Fn(&Repo) -> String,
    push: bool,
) -> Result<ScaffoldReport> {
    // 0. Fail closed on a dirty worktree: checkout would endanger content.
    let status = git(workdir, &["status", "--porcelain"])?;
    if !status.is_empty() {
        anyhow::bail!(
            "worktree at {} is dirty; commit or stash first",
            workdir.display()
        );
    }
    // 1. The control branch must not exist yet (never clobber).
    if git(
        workdir,
        &[
            "show-ref",
            "--verify",
            "--quiet",
            &format!("refs/heads/{}", opts.control_branch),
        ],
    )
    .is_ok()
    {
        // show-ref --quiet exits 0 when the ref exists.
        anyhow::bail!(
            "branch `{}` already exists; delete it or pick another --branch",
            opts.control_branch
        );
    }

    // 2. Resolve upstream tip + turn open PRs into patch proposals.
    let upstream_url = url_for(&opts.base.repo);
    let base_tip = crate::update::resolve_tip(&upstream_url, &opts.base.branch)?
        .with_context(|| format!("upstream branch `{}` not found", opts.base))?;
    let exclude = vec![
        opts.base.clone(),
        BranchRef {
            repo: opts.fork.clone(),
            branch: opts.output_branch.clone(),
        },
        BranchRef {
            repo: opts.fork.clone(),
            branch: opts.control_branch.clone(),
        },
    ];
    let patches = propose_patches(open, &exclude);

    // 3. Create the control branch: from the upstream tip, or a fresh root.
    if opts.fresh {
        git(workdir, &["checkout", "--orphan", &opts.control_branch])?;
        git(workdir, &["rm", "-rf", "."])?;
    } else {
        // Fetch the tip objects first so the branch has content to check out.
        git(
            workdir,
            &[
                "fetch",
                &upstream_url,
                &format!("{}:refs/remotes/synth-init-upstream", opts.base.branch),
            ],
        )?;
        git(
            workdir,
            &["checkout", "-b", &opts.control_branch, "FETCH_HEAD"],
        )?;
    }

    // 4. Write managed files and commit locally.
    let control = BranchRef {
        repo: opts.fork.clone(),
        branch: opts.control_branch.clone(),
    };
    let files = render_files(
        &opts.base,
        &opts.fork,
        &opts.output_branch,
        &control,
        &patches,
        &opts.engine_ref,
    );
    for (rel, content) in &files {
        let path = workdir.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create dir {}", parent.display()))?;
        }
        std::fs::write(&path, content).with_context(|| format!("write {}", path.display()))?;
    }
    let add_refs: Vec<&str> = files.iter().map(|(p, _)| p.as_str()).collect();
    let mut add_cmd = vec!["add", "--"];
    add_cmd.extend(add_refs);
    git(workdir, &add_cmd)?;
    git(
        workdir,
        &[
            "-c",
            "user.name=fork-maintainer",
            "-c",
            "user.email=fork-maintainer@users.noreply.github.com",
            "commit",
            "-qm",
            "managed synthesis setup (generated by synthesize --init)",
        ],
    )?;

    let report = ScaffoldReport {
        branch: opts.control_branch.clone(),
        files: files.into_iter().map(|(p, _)| p).collect(),
        patches: patches.clone(),
        base_tip,
        pushed: false,
    };

    if push {
        git(workdir, &["push", "origin", &opts.control_branch])?;
        return Ok(ScaffoldReport {
            pushed: true,
            ..report
        });
    }
    Ok(report)
}

/// What [`scaffold`] created, plus the human next steps.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScaffoldReport {
    /// Control branch created.
    pub branch: String,
    /// Files written, relative to the workdir.
    pub files: Vec<String>,
    /// Proposed patches in the generated config.
    pub patches: Vec<ProposedPatch>,
    /// Resolved upstream tip the branch forked (or tracked, when fresh).
    pub base_tip: gix::ObjectId,
    /// Whether `--push` pushed the branch.
    pub pushed: bool,
}

impl ScaffoldReport {
    /// The cutover sequence, printed after every run.
    pub fn next_steps(&self, fork: &Repo) -> String {
        format!(
            "review: git show --stat HEAD\n\
             push: git push origin {branch}\n\
             backup: git tag backup/pre-synthesis-$(date +%F) origin/{output} && git push origin backup/pre-synthesis-$(date +%F)\n\
             default: https://github.com/{fork}/settings — flip the default branch to {branch}\n\
             run: trigger the Synthesize workflow (manual dispatch), then review the bootstrapped lockfile\n\
             maintain: merge the weekly update PRs; never commit to the output directly",
            branch = self.branch,
            fork = fork.slug(),
            output = "main",
        )
    }
}

/// Resolve a default workdir: the current directory.
pub fn default_workdir() -> PathBuf {
    std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::update::OpenPr;

    fn pr(number: u64, owner: &str, name: &str, head: &str) -> OpenPr {
        OpenPr {
            number,
            head_owner: owner.into(),
            head_name: name.into(),
            head_ref: head.into(),
        }
    }

    fn bref(owner: &str, name: &str, branch: &str) -> BranchRef {
        BranchRef {
            repo: Repo {
                owner: owner.into(),
                name: name.into(),
            },
            branch: branch.into(),
        }
    }

    #[test]
    fn proposes_distinct_heads_by_pr_number() {
        let prs = vec![
            pr(20, "you", "r", "feat-b"),
            pr(12, "me", "r", "feat-a"),
            pr(13, "me", "r", "feat-a"), // same branch twice: first PR wins
        ];
        let out = propose_patches(&prs, &[]);
        assert_eq!(out.len(), 2);
        assert_eq!(out[0].pr_number, 12);
        assert_eq!(out[0].branch.branch, "feat-a");
        assert_eq!(out[1].pr_number, 20);
    }

    #[test]
    fn excludes_base_output_and_control() {
        let prs = vec![
            pr(1, "me", "r", "main"),
            pr(2, "me", "r", "fork-owned"),
            pr(3, "me", "r", "feature"),
        ];
        let exclude = vec![
            bref("up", "r", "main"),
            bref("me", "r", "main"),
            bref("me", "r", "fork-owned"),
        ];
        let out = propose_patches(&prs, &exclude);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].branch.branch, "feature");
    }

    #[test]
    fn render_includes_patches_and_pin() {
        let base = bref("up", "r", "main");
        let fork = Repo {
            owner: "me".into(),
            name: "r".into(),
        };
        let control = bref("me", "r", "fork-owned");
        let patches = vec![ProposedPatch {
            branch: bref("you", "o", "feat"),
            pr_number: 7,
        }];
        let files = render_files(&base, &fork, "main", &control, &patches, "abc123");
        let names: Vec<&str> = files.iter().map(|(p, _)| p.as_str()).collect();
        assert!(names.contains(&".github/workflows/synthesize.yml"));
        assert!(names.contains(&".github/workflows/update.yml"));
        assert!(names.contains(&"synthesis.json"));

        let config_raw = files
            .iter()
            .find(|(p, _)| p == "synthesis.json")
            .map(|(_, c)| c.as_str())
            .expect("config");
        let cfg: SynthesisConfig =
            serde_json::from_str(config_raw).expect("generated config parses");
        // Control branch leads unpinned; discovered patch pinned.
        assert_eq!(cfg.patches.len(), 2);
        assert_eq!(cfg.patches[0].branch.branch, "fork-owned");
        assert!(!cfg.patches[0].pin);
        assert_eq!(cfg.patches[1].branch.branch, "feat");
        assert!(cfg.patches[1].pin);

        let caller = files
            .iter()
            .find(|(p, _)| p == ".github/workflows/synthesize.yml")
            .map(|(_, c)| c.as_str())
            .expect("caller");
        assert!(caller.contains("abc123"), "engine pin embedded");
        assert!(
            caller.contains("config: synthesis.json"),
            "caller uses config-file mode"
        );
    }

    #[test]
    fn push_branches_only_same_repo() {
        let fork = Repo {
            owner: "me".into(),
            name: "r".into(),
        };
        let patches = vec![
            ProposedPatch {
                branch: bref("me", "r", "local-feat"),
                pr_number: 1,
            },
            ProposedPatch {
                branch: bref("you", "o", "remote-feat"),
                pr_number: 2,
            },
        ];
        assert_eq!(push_branches(&fork, &patches), "\"local-feat\"".to_string());
    }

    /// Scaffold end-to-end against local repos (no network, no API).
    #[test]
    fn scaffold_creates_branch_with_files() {
        let root = std::env::temp_dir().join(format!("init-e2e-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(&root).expect("mkdir");

        // Upstream bare repo with main.
        let upstream_dir = root.join("upstream.git");
        let upstream = gix::init_bare(&upstream_dir).expect("init upstream");
        let sig = gix::actor::SignatureRef::from_bytes(b"t <t@e.c> 1711398853 +0000").expect("sig");
        let blob = upstream.write_blob("base").expect("blob");
        let mut editor = upstream.edit_tree(upstream.empty_tree().id).expect("edit");
        editor
            .upsert("a.txt", gix::objs::tree::EntryKind::Blob, blob.detach())
            .expect("upsert");
        let tree = editor.write().expect("write").detach();
        let base = upstream
            .new_commit_as(sig, sig, "base", tree, None::<gix::ObjectId>)
            .expect("commit")
            .id;
        upstream
            .reference(
                "refs/heads/main",
                base,
                gix::refs::transaction::PreviousValue::Any,
                "init",
            )
            .expect("ref");

        // Workdir: a clone of an (empty-ish) fork repo.
        let fork_dir = root.join("fork.git");
        let _fork = gix::init_bare(&fork_dir).expect("init fork");
        let work = root.join("work");
        let status = std::process::Command::new("git")
            .args(["clone", "--quiet"])
            .arg(&fork_dir)
            .arg(&work)
            .status()
            .expect("clone");
        assert!(status.success());
        std::process::Command::new("git")
            .args(["-C"])
            .arg(&work)
            .args(["config", "user.email", "t@e.c"])
            .status()
            .expect("config");
        std::process::Command::new("git")
            .args(["-C"])
            .arg(&work)
            .args(["config", "user.name", "t"])
            .status()
            .expect("config");

        let opts = InitOptions {
            base: bref("up", "r", "main"),
            fork: Repo {
                owner: "me".into(),
                name: "r".into(),
            },
            output_branch: "main".into(),
            control_branch: "fork-owned".into(),
            fresh: false,
            engine_ref: "abc123".into(),
        };
        // file:// URL keeps it offline; upstream branch resolves locally.
        let upstream_url = format!("file://{}", upstream_dir.display());

        let report =
            scaffold(&work, &opts, &[], &|_| upstream_url.clone(), false).expect("scaffold");

        assert_eq!(report.branch, "fork-owned");
        assert_eq!(report.base_tip, base);
        assert!(!report.pushed, "no PRs offline, no push requested");
        assert!(report.files.contains(&"synthesis.json".to_string()));

        // The branch exists with the managed files committed.
        let shown = git(&work, &["show", "--name-only", "--format=", "fork-owned"]).expect("show");
        assert!(shown.contains("synthesis.json"), "got: {shown}");

        // The generated config parses with the control branch first.
        let raw = std::fs::read_to_string(work.join("synthesis.json")).expect("read");
        let cfg: SynthesisConfig = serde_json::from_str(&raw).expect("parses");
        assert_eq!(cfg.patches.len(), 1);
        assert!(!cfg.patches[0].pin);

        // Next steps render.
        assert!(report.next_steps(&opts.fork).contains("fork-owned"));
    }
}
